export const terms = {
  username: 'שם משתמש',
  signIn: 'כניסה',
  confirmPassword: 'אימות סיסמה',
  signUp: 'הרשמה',
  doesNotMatchPassword: 'לא תואם לסיסמה',
  password: 'סיסמה',
  updateInfo: 'עדכון פרטים',
  changePassword: 'שינוי סיסמה',
  hello: 'שלום',
  invalidOperation: 'פעולה לא חוקית',
  admin: 'אדמין',
  manager: 'מנהל',
  disabled: 'לא פעיל',
  yes: 'כן', 
  no: 'לא',
  ok: 'אישור',
  areYouSureYouWouldLikeToDelete: 'האם אתה בטוח שברצונך למחוק',
  cancel: 'ביטול',
  close: 'סגור',
  home: 'דף הבית',
  userAccounts: 'משתמשים',
  invalidSignIn: 'פרטי התחברות שגויים',
  signOut: 'יציאה',
  resetPassword: 'איפוס סיסמה',
  passwordDeletedSuccessful: 'הסיסמה נמחקה בהצלחה',
  passwordDeleteConfirmOf: 'האם אתה בטוח שברצונך למחוק את הסיסמה של',
  rememberOnThisDevice: 'זכור אותי במכשיר זה',
  RTL: true,
  requiredFiled: 'שדה חובה',
  uniqueFiled: 'שדה קיים כבר',
  createDate: 'תאריך יצירה'
}